# Generated by Django 2.1.3 on 2018-11-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_url_tempuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shorten_url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
