# Generated by Django 2.1.3 on 2018-11-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_auto_20181118_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
