# Generated by Django 2.1.3 on 2018-12-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0005_auto_20181118_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shorten_url',
            field=models.CharField(max_length=50),
        ),
    ]
