# Generated by Django 2.2.8 on 2020-01-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0006_auto_20181202_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=20)),
                ('enable_hours', models.BooleanField()),
                ('enable_week', models.BooleanField()),
                ('enable_month', models.BooleanField()),
            ],
        ),
    ]
